# Generated by Django 5.0.1 on 2024-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_about',
            field=models.CharField(default='img', max_length=300, verbose_name='About author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author_img',
            field=models.ImageField(default='about', upload_to='image/author', verbose_name='Author image'),
            preserve_default=False,
        ),
    ]
