# Generated by Django 5.0.1 on 2024-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_author_about_post_author_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_about',
            field=models.CharField(max_length=500, verbose_name='About author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_img',
            field=models.ImageField(upload_to='images/author', verbose_name='Author image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='images/%Y', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Post Title'),
        ),
    ]
