# Generated by Django 5.0.1 on 2024-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='images/shop', verbose_name='Product image'),
        ),
    ]
